const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');
{
  const vm=require('vm');let values={},fail=false;const context={window:{},localStorage:{getItem:k=>values[k]??null,setItem:(k,v)=>{if(fail&&k==='cites-animals')throw Error('quota');values[k]=v;},removeItem:k=>{delete values[k];}}};
  vm.runInNewContext(fs.readFileSync(path.join(root,'js/record-store.js'),'utf8'),context);
  const records=context.window.CitesRecords;
  values['cites-animals']=JSON.stringify([{id:'a',species:'테라핀'}]);
  values['cites-documents']=JSON.stringify([{id:'d',title:'기존',speciesEntries:[{species:'테라핀',count:2}],initialCount:2,animalIds:[],quantityChanges:[{species:'테라핀',count:2}]}]);
  const input={id:'d',title:'수정',speciesEntries:[{species:'테라핀',count:1}],animalIds:[]};
  assert.throws(()=>records.saveDocument(input,true),/수량/);
  input.speciesEntries[0].count=2;input.animalIds=['a'];assert.throws(()=>records.saveDocument(input,true),/남은 수량/);
  input.animalIds=[];records.saveDocument(input,true);assert.equal(JSON.parse(values['cites-documents'])[0].quantityChanges[0].count,2);
  values['cites-documents']=JSON.stringify([{id:'d',animalIds:['a']}]);values['cites-breeding-records']=JSON.stringify([{id:'b',animalId:'a'}]);const before=JSON.stringify(values);fail=true;assert.throws(()=>records.deleteAnimal('a'),/저장/);assert.equal(JSON.stringify(values),before);
  console.log('PASS decrease-history protection, exhausted document rejection, atomic delete rollback');
}
(async()=>{
const server=http.createServer((req,res)=>{const f=path.join(root,new URL(req.url,'http://local').pathname);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':'text/html; charset=utf-8');res.end(fs.readFileSync(f));}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
let browser;try{
browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||undefined});const page=await browser.newPage();const base='http://127.0.0.1:'+server.address().port;const errors=[];page.on('pageerror',e=>errors.push(e.message));let accept=true,warning='';page.on('dialog',async d=>{warning=d.message();await(accept?d.accept():d.dismiss());});
await page.goto(base+'/documents.html');
const entry={species:'테라핀',scientificName:'Malaclemys terrapin',count:1};const a={id:'a',name:'원본',category:'거북이',species:'테라핀',scientificName:'Malaclemys terrapin',status:'보유 중',sex:'암컷',date:'2020-01-01',memo:'기존 메모',createdAt:'2020-01-01',photo:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aDnsAAAAASUVORK5CYII=',drivePhotoId:'photo-backup'};
const docs=[{id:'d',title:'원본 서류',reference:'REF-1',species:'테라핀',speciesEntries:[entry],initialCount:1,animalIds:['a'],quantityChanges:[],fileName:'original.pdf',fileData:'data:application/pdf;base64,JVBERg==',driveFileId:'backup',createdAt:'2020-01-01'},{id:'spare',title:'여유 서류',species:'테라핀',speciesEntries:[{...entry,count:3}],initialCount:3,animalIds:[],quantityChanges:[],createdAt:'2020-01-01'}];
await page.evaluate(({a,docs})=>{localStorage.setItem('cites-animals',JSON.stringify([a]));localStorage.setItem('cites-documents',JSON.stringify(docs));localStorage.setItem('cites-breeding-records',JSON.stringify([{id:'b',animalId:'a'},{id:'other',animalId:'other'}]));},{a,docs});
await page.goto(base+'/animal-detail.html?id=a');await page.locator('#document-toggle').click();assert.equal(await page.locator('#document-title').count(),0);assert.equal(await page.locator('#existing-documents input[value=d]').isChecked(),true);
await page.locator('#existing-documents input[value=d]').uncheck();await page.locator('#document-cancel').click();await page.locator('#document-toggle').click();assert.equal(await page.locator('#existing-documents input[value=d]').isChecked(),true);await page.locator('#document-form button[type=submit]').click();
await page.getByText('이 동물 복사 등록',{exact:true}).click();await page.waitForURL('**/*copy=a');assert.equal(await page.locator('#animal-name').inputValue(),'');assert.equal(await page.locator('#sex').inputValue(),'암컷');assert.equal(await page.locator('#document-candidates input:checked').count(),0);
await page.locator('#document-candidates input[value=d]').click();assert.equal(await page.locator('#document-candidates input[value=d]').isChecked(),false);assert.match(warning,/수량/);
await page.locator('#animal-name').fill('복사 동물');await page.locator('#document-candidates input[value=spare]').check();await page.locator('#next').click();await page.locator('#next').click();await page.locator('#done').click();await page.waitForURL('**/animal-detail.html?id=*');let copied=await page.evaluate(()=>JSON.parse(localStorage.getItem('cites-animals'))[0]);assert.notEqual(copied.id,'a');assert.equal(copied.photo,'');
await page.getByText('정보 수정',{exact:true}).click();await page.waitForURL('**/*edit=*');await page.locator('#animal-name').fill('수정 동물');await page.locator('#memo').fill('새 메모');await page.locator('#next').click();await page.locator('#next').click();await page.locator('#done').click();await page.waitForURL('**/animal-detail.html?id=*');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cites-animals')).length),2);assert.equal(await page.locator('h1').innerText(),'수정 동물');
await page.goto(base+'/animal-register.html?edit=a');await page.locator('#animal-name').fill('원본 수정');await page.locator('#next').click();await page.locator('#next').click();await page.locator('#done').click();await page.waitForURL('**/animal-detail.html?id=a');const original=await page.evaluate(()=>JSON.parse(localStorage.getItem('cites-animals')).find(a=>a.id==='a'));assert.equal(original.photo,a.photo);assert.equal(original.drivePhotoId,'photo-backup');assert.equal(original.createdAt,a.createdAt);
for(const width of [1280,375,320]){await page.setViewportSize({width,height:900});await page.locator('#document-toggle').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(process.env.TEST_SCREENSHOTS)await page.screenshot({path:path.join(process.env.TEST_SCREENSHOTS,'crud-detail-'+width+'.png'),fullPage:true});}
console.log('PASS existing document picker, warning/blocked excess, copy, animal edit identity/photo preservation, responsive detail');
await page.goto(base+'/documents.html');await page.locator('[data-edit-document=d]').click();await page.locator('#document-title').fill('수정 서류');await page.locator('#document-reference').fill('REF-2');await Promise.all([page.waitForEvent('domcontentloaded'),page.locator('#document-form button[type=submit]').click()]);let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('cites-documents')).find(d=>d.id==='d'));assert.equal(saved.title,'수정 서류');assert.equal(saved.fileData,docs[0].fileData);assert.equal(saved.driveFileId,'backup');assert.deepEqual(saved.animalIds,['a']);
await page.locator('[data-edit-document=spare]').click();await page.locator('.species-count').fill('1');await page.locator('input[name=document-animal][value=a]').check();await page.locator('#document-form button[type=submit]').click();assert.match(warning,/수량/);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cites-documents')).find(d=>d.id==='spare').initialCount),3);
await page.locator('#document-cancel').click();accept=false;await page.locator('[data-delete-document=d]').click();assert.equal(await page.locator('[data-delete-document=d]').count(),1);accept=true;await Promise.all([page.waitForEvent('domcontentloaded'),page.locator('[data-delete-document=d]').click()]);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cites-documents')).length),1);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cites-animals')).length),2);
await page.goto(base+'/animal-detail.html?id=a');accept=false;await page.locator('#animal-delete').click();assert.equal(await page.locator('h1').innerText(),'원본 수정');accept=true;await page.locator('#animal-delete').click();await page.waitForURL('**/animals.html');const remaining=await page.evaluate(()=>({animals:JSON.parse(localStorage.getItem('cites-animals')),docs:JSON.parse(localStorage.getItem('cites-documents')),records:JSON.parse(localStorage.getItem('cites-breeding-records'))}));assert.equal(remaining.animals.length,1);assert.equal(remaining.docs.length,1);assert.deepEqual(remaining.records,[{id:'other',animalId:'other'}]);assert(!remaining.docs.some(d=>d.animalIds.includes('a')));
console.log('PASS document edit attachment/history preservation, quantity reduction rejection, delete confirmation/cancel and linked-record cleanup');assert.deepEqual(errors,[]);
}finally{if(browser)await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
